//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mall_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Space
    {
        public int SpaceID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string SpaceName { get; set; }
        public Nullable<decimal> Size { get; set; }
        public string Location { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> RentalPrice { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
